In [60]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
#import warnings
#warnings.filterwarnings('ignore')
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

For this lab, you will be using the .CSV files provided in the files_for_lab folder. These are cleaned versions of the learningSet data from the Case Study 'Healthcare for All'.
Begin a new Jupyter Notebook after Forking and Cloning this Repo.

DATAFRAME

In [95]:
numerical = pd.read_csv('numerical.csv')
categorical = pd.read_csv('categorical.csv')
targets = pd.read_csv('target.csv')
data = pd.concat([numerical, categorical, targets], axis = 1)
data['TARGET_B'].value_counts()

0    90569
1     4843
Name: TARGET_B, dtype: int64

Apply the Random Forests algorithm but this time only by upscaling the data to deal with the imbalance.

In [96]:
y = data['TARGET_B']
X = data.drop(['TARGET_B'], axis = 1) 

numericalX = X.select_dtypes(np.number)
categoricalX = X.select_dtypes(object)

# we OneHotEncode the categoricals so we can use the same dataset to perform a regression later (in the lab).
# it is not needed for a DecisionTree or RandomForest model
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first').fit(categoricalX)
encoded_categorical = encoder.transform(categoricalX).toarray()
encoded_categorical = pd.DataFrame(encoded_categorical, columns=encoder.get_feature_names_out()) # needed to avoid error
X = pd.concat([numericalX, encoded_categorical], axis = 1)

# Note: we need to do train/test split before downsampling, and then only downsample the training set - Why?
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [97]:
from sklearn.utils import resample

In [98]:
# for upsampling we need to temporarily concat X_train and y_train
trainset = pd.concat([X_train, y_train], axis=1)
# quicker way to upsample category 1:

category_0 = trainset[trainset['TARGET_B'] == 0]
category_1 = trainset[trainset['TARGET_B'] == 1]
category_1 = resample(category_1,replace=True, n_samples = len(category_0))
print(category_0.shape)
print(category_1.shape)

trainset_new = pd.concat([category_0, category_1], axis = 0)
trainset_new = trainset_new.sample(frac =1) #randomize the rows
X_train = trainset_new.drop(['TARGET_B'], axis=1)
y_train = trainset_new['TARGET_B']
# #data = data.reset_index(drop=True)
print(X_train.shape)

(72486, 356)
(72486, 356)
(144972, 355)


In [99]:
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

y_train_regression = X_train['TARGET_D']
y_test_regression = X_test['TARGET_D']

# Now we can remove the column target d from the set of features
X_train = X_train.drop(['TARGET_D'], axis = 1)
X_test = X_test.drop(['TARGET_D'], axis = 1)

In [100]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

clf = RandomForestClassifier(max_depth=5, # max number of questions to ask
                             min_samples_split=20, # amount of rows still considered at every question
                             min_samples_leaf =20, # ultimate answer based on at least this many rows
                             max_samples=0.8, # fraction of X-train to use in each tree
                             random_state=42)
clf.fit(X_train, y_train)
all_feat_train_score = clf.score(X_train, y_train)
print(all_feat_train_score)
all_feat_test_score = clf.score(X_test, y_test)
print(all_feat_test_score)

y_pred = clf.predict(X_test)
display(y_test.value_counts())
all_confusion_matrix = confusion_matrix(y_test, y_pred)
display(all_confusion_matrix)

0.6234307314515907
0.5979143740502018


0    18083
1     1000
Name: TARGET_B, dtype: int64

array([[10853,  7230],
       [  443,   557]])

Use Feature Selections that you have learned in class to decide if you want to use all of the features (Variance Threshold, RFE, PCA, etc.)

FIRST! ENCONDE AND MIN-MAX

In [ ]:
y = data['TARGET_B']
X = data.drop(['TARGET_B'], axis = 1)

numericalX = X.select_dtypes(np.number)
categoricalX = X.select_dtypes(object)

#ONE ENCODE CATEGORICALS
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first').fit(categoricalX)
encoded_categorical = encoder.transform(categoricalX).toarray()
encoded_categorical = pd.DataFrame(encoded_categorical, columns=encoder.get_feature_names_out()) # needed to avoid error
X = pd.concat([numericalX, encoded_categorical], axis = 1)

#MIN-MAX NUMERICAL NORMALIZED WITH ENCODED_CATEGORICAL, NOW ARE DATAFRAME IT'S READY TO TAKE A RFE.
from sklearn.preprocessing import MinMaxScaler
transformer= MinMaxScaler().fit(numericalX)
numericalX = pd.DataFrame(transformer.transform(numericalX), columns=numericalX.columns)
X = pd.concat([numericalX, encoded_categorical], axis = 1)

#TO MAKE IT 100% RIGHT IT SHOULD HAVE BEEN SPLIT INTO TRAIN AND TEST, FIT THE MODEL WITH TRAIN AND THEN TEST, BUT THAT WAS DONE YESTERDAY, JUST TRYING NEW FEATURE SELECTION WITHOUT GOING CRAZY


Recrusive Feature Elimination

In [ ]:
import pandas as pd
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [ ]:
X.head()

TCODE       AGE    INCOME   WEALTH1       HIT  MALEMILI   MALEVET  \
0  0.000000  0.608247  0.666667  1.000000  0.000000  0.000000  0.393939   
1  0.000014  0.463918  0.833333  1.000000  0.066390  0.000000  0.151515   
2  0.000014  0.624862  0.333333  0.111111  0.008299  0.000000  0.202020   
3  0.000000  0.711340  0.000000  0.444444  0.008299  0.000000  0.232323   
4  0.000000  0.793814  0.333333  0.222222  0.248963  0.010101  0.282828   

   VIETVETS  WWIIVETS  LOCALGOV  STATEGOV    FEDGOV   WEALTH2    POP901  \
0  0.343434  0.181818  0.101010  0.020202  0.011494  0.555556  0.010051   
1  0.555556  0.111111  0.060606  0.020202  0.011494  1.000000  0.036585   
2  0.292929  0.333333  0.060606  0.080808  0.011494  0.111111  0.070931   
3  0.141414  0.313131  0.030303  0.000000  0.034483  0.000000  0.006484   
4  0.090909  0.535354  0.262626  0.030303  0.022989  1.000000  0.025532   

     POP902    POP903  POP90C1   POP90C2   POP90C3   POP90C4   POP90C5  \
0  0.011108  0.009378      0.0  0.353535  0.656566  0.474747  0.535354   
1  0.039552  0.028190      1.0  0.000000  0.000000  0.505051  0.505051   
2  0.085837  0.075389      0.0  0.020202  0.989899  0.494949  0.515152   
3  0.006732  0.006186      0.0  0.080808  0.929293  0.545455  0.464646   
4  0.026382  0.021495      1.0  0.000000  0.000000  0.464646  0.545455   

       ETH1      ETH2  ETH3      ETH4      ETH5      ETH6      ETH7      ETH8  \
0  0.929293  0.010101   0.0  0.000000  0.111111  0.000000  0.000000  0.000000   
1  0.676768  0.000000   0.0  0.313131  0.060606  0.181818  0.027778  0.060606   
2  0.969697  0.020202   0.0  0.000000  0.020202  0.000000  0.000000  0.000000   
3  0.616162  0.000000   0.0  0.111111  0.323232  0.272727  0.027778  0.000000   
4  0.020202  0.989899   0.0  0.000000  0.010101  0.000000  0.000000  0.000000   

       ETH9     ETH10  ETH11  ETH12     ETH13  ETH14     ETH15     ETH16  \
0  0.000000  0.000000    0.0    0.0  0.113402    0.0  0.000000  0.000000   
1  0.059701  0.304348    0.0    0.0  0.020619    0.0  0.012346  0.046512   
2  0.000000  0.000000    0.0    0.0  0.020619    0.0  0.000000  0.000000   
3  0.000000  0.000000    0.0    0.0  0.319588    0.0  0.000000  0.011628   
4  0.000000  0.000000    0.0    0.0  0.000000    0.0  0.000000  0.000000   

     AGE901    AGE902    AGE903    AGE904    AGE905    AGE906    AGE907  \
0  0.464286  0.571429  0.607143  0.476190  0.595238  0.642857  0.333333   
1  0.404762  0.488095  0.511905  0.380952  0.500000  0.535714  0.426667   
2  0.416667  0.511905  0.547619  0.440476  0.535714  0.583333  0.306667   
3  0.380952  0.476190  0.523810  0.404762  0.511905  0.559524  0.333333   
4  0.392857  0.535714  0.595238  0.428571  0.547619  0.595238  0.360000   

      CHIL1     CHIL2     CHIL3     AGEC1     AGEC2     AGEC3     AGEC4  \
0  0.313131  0.424242  0.272727  0.111111  0.141414  0.181818  0.171717   
1  0.333333  0.464646  0.212121  0.131313  0.141414  0.333333  0.232323   
2  0.353535  0.404040  0.252525  0.131313  0.202020  0.191919  0.161616   
3  0.454545  0.353535  0.202020  0.151515  0.252525  0.171717  0.171717   
4  0.343434  0.434343  0.232323  0.141414  0.212121  0.131313  0.151515   

      AGEC5     AGEC6     AGEC7    CHILC1    CHILC2    CHILC3    CHILC4  \
0  0.131313  0.111111  0.151515  0.121212  0.111111  0.343434  0.252525   
1  0.101010  0.040404  0.020202  0.111111  0.161616  0.363636  0.222222   
2  0.131313  0.101010  0.080808  0.151515  0.141414  0.303030  0.222222   
3  0.121212  0.070707  0.070707  0.202020  0.171717  0.303030  0.141414   
4  0.202020  0.121212  0.050505  0.131313  0.151515  0.343434  0.191919   

     CHILC5    HHAGE1    HHAGE2    HHAGE3      HHN1      HHN2      HHN3  \
0  0.181818  0.262626  0.101010  0.232323  0.181818  0.333333  0.494949   
1  0.151515  0.121212  0.010101  0.050505  0.040404  0.212121  0.757576   
2  0.191919  0.252525  0.101010  0.232323  0.212121  0.353535  0.444444   
3  0.191919  0.252525  0.111111  0.232323  0.232323  0.272727 

In [ ]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: TARGET_B, dtype: int64

In [ ]:
num_features_to_select = 10
rfe = RFE(estimator=LogisticRegression(), n_features_to_select=num_features_to_select)

In [ ]:
#rfe.fit(X, y)
#22 MINUTES 11s IN A MACBOOK AIR 8GB RAM, DON'T RUN IT

/Users/agustinredondoarena/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/agustinredondoarena/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/l

RFE(estimator=LogisticRegression(), n_features_to_select=10)

In [ ]:
feature_ranking = rfe.support_
feature_ranking 

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [ ]:
selected_columns = X.columns[feature_ranking]
selected_features_X = X[selected_columns]
selected_features_X

CHILC2      HHD9  LASTGIFT   AVGGIFT    RFA_2F  ODATEW_YR  ODATEW_MM  \
0      0.111111  0.050505     0.010  0.006465  1.000000   0.428571        0.0   
1      0.161616  0.030303     0.025  0.014399  0.333333   0.785714        0.0   
2      0.141414  0.050505     0.005  0.006204  1.000000   0.500000        0.0   
3      0.171717  0.030303     0.010  0.005534  1.000000   0.285714        0.0   
4      0.151515  0.171717     0.015  0.005586  0.333333   0.214286        0.0   
...         ...       ...       ...       ...       ...        ...        ...   
95407  0.181818  0.101010     0.025  0.023745  0.000000   0.928571        0.0   
95408  0.161616  0.010101     0.020  0.018738  0.000000   0.928571        0.0   
95409  0.171717  0.141414     0.010  0.007009  0.666667   0.857143        0.0   
95410  0.161616  0.060606     0.018  0.010875  1.000000   0.214286        0.0   
95411  0.181818  0.040404     0.100  0.095632  0.000000   0.357143        0.0   

       MINRDATE_YR  TARGET_D  RFA_2A_G  
0         0.772727      0.00       0.0  
1         0.818182      0.00       1.0  
2         0.727273      0.00       0.0  
3         0.545455      0.00       0.0  
4         0.818182      0.00       0.0  
...            ...       ...       ...  
95407     0.954545      0.00       1.0  
95408     0.954545      0.00       0.0  
95409     0.954545      0.00       0.0  
95410     0.681818      0.09       0.0  
95411     0.590909      0.00       1.0  

[95412 rows x 10 columns]

Re-run the Random Forest algorithm to determine if the Feature Selection has improved the results.

In [101]:
y1 = data['TARGET_B']
X1 = selected_features_X

In [102]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=0)

In [103]:
# for upsampling we need to temporarily concat X_train and y_train
trainset1 = pd.concat([X1_train, y1_train], axis=1)
# quicker way to upsample category 1:

category_0_1 = trainset1[trainset1['TARGET_B'] == 0]
category_1_1 = trainset1[trainset1['TARGET_B'] == 1]
category_1_1 = resample(category_1_1,replace=True, n_samples = len(category_0_1))
print(category_0_1.shape)
print(category_1_1.shape)

trainset_new_1 = pd.concat([category_0_1, category_1_1], axis = 0)
trainset_new_1 = trainset_new_1.sample(frac =1) #randomize the rows
X1_train = trainset_new_1.drop(['TARGET_B'], axis=1)
y1_train = trainset_new_1['TARGET_B']
# #data = data.reset_index(drop=True)
print(X1_train.shape)

(72486, 11)
(72486, 11)
(144972, 10)


In [104]:
X1_train = pd.DataFrame(X1_train)
X1_test = pd.DataFrame(X1_test)

y1_train_regression = X1_train['TARGET_D']
y1_test_regression = X1_test['TARGET_D']

# Now we can remove the column target d from the set of features
X1_train = X1_train.drop(['TARGET_D'], axis = 1)
X1_test = X1_test.drop(['TARGET_D'], axis = 1)

In [110]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

clf1 = RandomForestClassifier(max_depth=5, # max number of questions to ask
                             min_samples_split=20, # amount of rows still considered at every question
                             min_samples_leaf =20, # ultimate answer based on at least this many rows
                             max_samples=0.8, # fraction of X-train to use in each tree
                             random_state=42)
clf1.fit(X1_train, y1_train)
selected_train_score = clf1.score(X1_train, y1_train)
print(selected_train_score)
selected_test_score = clf1.score(X1_test, y1_test)
print(selected_test_score)

y1_pred = clf1.predict(X1_test)
selected_confusion_matrix = confusion_matrix(y1_test, y1_pred)
display(y1_test.value_counts())
display(selected_confusion_matrix)

0.5927489446237895
0.6168841377141959


0    18083
1     1000
Name: TARGET_B, dtype: int64

array([[11249,  6834],
       [  477,   523]])

DISCUSSION COMPARING RESULTS: UPSAMPLING BOTH, MAKING AN RFE ON THE SECOND ONE

In [107]:
all_feat_train_score = clf.score(X_train, y_train)
print(all_feat_train_score)
all_feat_test_score = clf.score(X_test, y_test)
print(all_feat_test_score)

display(y_test.value_counts())
all_confusion_matrix = confusion_matrix(y_test, y_pred)
display(all_confusion_matrix)

0.6234307314515907
0.5979143740502018


0    18083
1     1000
Name: TARGET_B, dtype: int64

array([[10853,  7230],
       [  443,   557]])

In [111]:
selected_train_score = clf1.score(X1_train, y1_train)
print(selected_train_score)
selected_test_score = clf1.score(X1_test, y1_test)
print(selected_test_score)

selected_confusion_matrix = confusion_matrix(y1_test, y1_pred)
display(y1_test.value_counts())
display(selected_confusion_matrix)

0.5927489446237895
0.6168841377141959


0    18083
1     1000
Name: TARGET_B, dtype: int64

array([[11249,  6834],
       [  477,   523]])

We get a similar explanatory power (0.6), in the selected feautures we are better in predicting who had a 1 (who donated), and has a lower error when predicting who hasn't donated. With all the columns, we have less errors but we get also a lower number when predicting donors (1/1)